# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opt_crossprod <- function(A, B, n) {
    .Call('_DRDID_opt_crossprod', PACKAGE = 'DRDID', A, B, n)
}

batch_matrix_operations <- function(wols_eX, XpX_inv, score_ps, Hessian_ps, M1, M2, M3) {
    .Call('_DRDID_batch_matrix_operations', PACKAGE = 'DRDID', wols_eX, XpX_inv, score_ps, Hessian_ps, M1, M2, M3)
}

checkTreatmentUniqueness <- function(dta, idname, treatName) {
    invisible(.Call('_DRDID_checkTreatmentUniqueness', PACKAGE = 'DRDID', dta, idname, treatName))
}

